"""baseline: lead, dailyusage

Revision ID: 52db5c201eaf
Revises: 
Create Date: 2026-06-24 11:30:54.597856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated ops


# revision identifiers, used by Alembic.
revision: str = '52db5c201eaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyusage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('need', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timeline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_session_id'), 'lead', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_session_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_table('dailyusage')
    # ### end Alembic commands ###
